"""Digest markdown composer."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from rss_digest.models import Group, Item, ItemSummary


@dataclass
class DigestSection:
    title: str
    url: str
    summary: str


class DigestBuilder:
    def compose(
        self,
        group: Group,
        scheduled_at: datetime,
        sections: list[DigestSection],
    ) -> str:
        lines = [
            f"# {group.name} / {scheduled_at:%Y-%m-%d %H:%M}",
            "",
            "## 今日のまとめ（3行）",
        ]
        summary_lines = [f"- {section.title}" for section in sections[:3]]
        if not summary_lines:
            summary_lines = ["- 収集された記事はありませんでした。"]
        lines.extend(summary_lines)
        lines.append("")
        lines.append("## カテゴリ: General")
        for section in sections:
            lines.append(f"### {section.title}")
            lines.append(f"- 要約: {section.summary}")
            lines.append(f"- URL: {section.url}")
            lines.append("")
        lines.append("---")
        lines.append("Generated by RSS Digest")
        return "\n".join(lines)

    @staticmethod
    def from_items(
        items: list[Item],
        summaries: list[ItemSummary],
    ) -> list[DigestSection]:
        summary_map = {summary.item_id: summary.summary_md for summary in summaries}
        sections: list[DigestSection] = []
        for item in items:
            sections.append(
                DigestSection(
                    title=item.canonical_url,
                    url=item.canonical_url,
                    summary=summary_map.get(item.id, ""),
                )
            )
        return sections
